name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Runs this script every time you push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Application
        # IMPORTANT: Change base-href to match your repository name
        run: flutter build web --release --base-href "/queens_gambit/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages # Pushes the build to this separate branch
